a = int(input("A soni kiriting - "))
b = int(input("B soni kiriting - "))
print("A va B sonlari yig'disi = ",a+b)
print("A va B sonlari ayirmasi = ",a-b)
print("A va B sonlari ko'paytmasi = ",a*b)
print("A va B sonlari bo'linmasi = ",a/b)